### ISSUE TITLE
EPIC: Create Bolus Calculator

### ISSUE THREAD

**Issue by robflowerday** [robflowerday/Diabetes#11]
Create a bolus calculator that determines the number of insulin units needed as the sum of
- The meal bolus dose
    - Should be optional depending on whether no. carbs eaten is provided
    - Can be 0
    - Should not be negative
- The correction bolus dose
    - Should be optional depending on whether current glucose level is provided
    - Can be positive, 0 or negative
- The negative of the Bolus insulin already on board
    - Bolus insulin already on board should not be negative
    - At first we shouldn't be able to override this

- [ ]  https://github.com/robflowerday/Diabetes/issues/12
- [ ] https://github.com/robflowerday/Diabetes/issues/13
- [ ] https://github.com/robflowerday/Diabetes/issues/14
- [ ] Create issue and functionality for bolus calculator that takes relevant inputs and all of these above calculations into account
